name: Donation
description: AB Project-ee.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  web: any
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendRegular.ttf
          weight: 400

flutter_native_splash:
  color: "#ffffff" # Couleur d’arrière-plan
  image: assets/icon/splash.png #  image splash (format recommandé : 4x la taille de ton icône)
  branding: assets/icon/img_ellipse_2.svg # (optionnel) petit logo en bas
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # ← image carrée
  min_sdk_android: 21 # optionnel
